### PR TITLE
Fix Custom schemas in `mdf_reader` module

### PR DESCRIPTION
**Pull request by jtsiddons**
Loading of custom schema & opening source files fails if `data_model_path` argument is used in `mdf_reader.read`.

This PR corrects loading of schema depending if `data_model` or `data_model_path` arguments are used. 

Also corrects opening of the data since `properties.open_file` is not set for custom models, hence `open_with` gets set to `None`. Instead default to "pandas".

Also update 2 of the notebooks, accounting for the above changes and removing absolute paths that were for a specific user.

### CODE REVIEW

**Comment by jtsiddons** [comment]
@ludwiglierhammer : There is another notebook with absolute paths (example_notebooks/CLIWOC_missing_code_tables.ipynb)

The data required for this notebook doesn't appear to exist within the test data repository. I look to see if I can find the data used & correct this notebook if desired - alternatively maybe it can be removed?

**Comment by ludwiglierhammer** [comment]
@jtsiddons: Many thanks for this PR. I haven't tested any custom schemas yet. This is very helpful 😄. I just took all the notebooks from the previous [cmd_mapper](https://github.com/glamod/cdm-mapper) and [mdf_reader](https://github.com/glamod/mdf_reader/tree/backup) packages without any adjustments.    
Do not worry about the failed testing suite, I made some changes to the CDM mapping: see https://github.com/glamod/cdm_reader_mapper/pull/37. This should be fixed as soon as I merge the PR.

**Comment by jtsiddons** [comment]
@ludwiglierhammer : Thanks for the information on the tests, I had noticed they failed on `main` too. I'll ask around about the missing data for the other notebook, amend if I can, then remove the draft tag.

**Comment by jtsiddons** [comment]
I have removed the additional notebook, I'm not sure it works as an example notebook.

**Comment by jtsiddons** [comment]
Using simple schema such as

```json
{
    "header": {
        "delimiter": ";",
        "format": "delimited",
        "field_layout": "delimited"
    },
    "elements": {
        "Year": {
            "column_type": "uint16",
            "units": "metre",
            "valid_max": 1878,
            "valid_min": 1876,
            "description": "Year (m)"
        },
        "Sea Swell": {
            "column_type": "key",
            "code_table": "sea_swell",
            "units": null,
            "description": "Sea Swell (None)"
        }
    }
}
```

Fails in `mdf_reader.read`, with logging.error to set "field_layout" or "format" in header. This message arises following `mdf_reader.utils.auxillery.Configurator.open_pandas()` when it calls `self._get_borders`. This function eventually calls `Configurator._validate_delimited` which checks `self.delimited_format`. This attr should be set to the section header `format` field, which is not set for the example above (despite the field being set in the schema).

Fix was to ensure this field is passed from the header to section headers in cases like the above. [228ae66](https://github.com/glamod/cdm_reader_mapper/pull/40/commits/228ae66ce0575813816c5759a667d4c217c85011)

**Comment by ludwiglierhammer** [comment]
@jtsiddons Many thanks for checking custom schemas. Do you think we can or should add some tests for custom schemas to the testing suite? Then, I think I can merge this PR. Or do you have any further adjustments?

**Comment by jtsiddons** [comment]
@ludwiglierhammer I think adding extra tests for this is a good idea. I assume any additional tests will need to be part of [glamod/cdm-testdata](https://github.com/glamod/cdm-testdata)? I'll have a look into it, although that will likely be mid-week sometime. 

A brief look suggests I'll need to modify https://github.com/glamod/cdm_reader_mapper/blob/main/tests/_testing_cdm_suite.py#L67 to allow for `data_model_path` argument.

At some point, I want to look into custom models and the mapper, but I've not started looking into that component yet. That won't be part of this PR.

**Comment by ludwiglierhammer** [comment]
@jtsiddons: Pretty good :tada: 
I'll merge this PR into the main branch. Could you please add your changes to the [changes history](https://github.com/glamod/cdm_reader_mapper/blob/main/CHANGES.rst).
For the additonal test I'll open a new issue for discussion.

**Comment by jtsiddons** [comment]
@ludwiglierhammer Do you want me to add the changes as a new PR?

**Comment by ludwiglierhammer** [comment]
@jtsiddons: sorry, I shouldn't have merged this PR yet 😵 
You can send me your changes as a comment and I'll add them to the ``CHANGES.rst``

**Comment by jtsiddons** [comment]
@ludwiglierhammer No worries - I think I missed the merge by about 2 minutes with a changelog commit on my branch!

I had added the following to the bug fixes section

```rst
* fix reading of custom schema in ``mdf_reader.read`` (:pull:`40`)
* ensure ``format`` schema field for delimited files is passed correctly, avoiding ``"...Please specify either format or field_layout in your header schema..."`` error (:pull:`40`)
```

and the following to contributors:

```rst
Contributors to this version: Ludwig Lierhammer (:user:`ludwiglierhammer`), Joseph Siddons (:user:`jtsiddons`)
```

**Comment by ludwiglierhammer** [comment]
@jtsiddons Done ✔️

**Pull request merged**
